version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - new-net
    
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    container_name: nodeapp
    networks:
      - new-net
    depends_on: 
      - mongodb  

networks:
    new-net:
