version: "3"
services:
  nodeapp:
    restart: always
    build: .
    ports:
      - "3000:3000"
    container_name: node
    volumes:
      - ./:/app
      - /app/node_modules

  #   links:
  #     - mongodb
  #
  # mongodb:
  #   image: mongo
  #   container_name: db
  #   volumes:
  #     - /var/www/node-mongo-docker/data:/data/db/
  #   ports:
  #     - "27017:27017"
